version: "2.2"

services:
  # app:
  #   build: "."
  #   environment:
  #     - CTP_PROJECT_KEY=demo-1
  #   volumes:
  #     - ./.data:/usr/app/.data
  #   cpus: "0.5"
  #   mem_limit: 512m

  # uncomment the services below to run in non apps separately

  app1:
    build: "./app1"
    env_file:
      - ./app1/.env
    volumes:
      - ./.data:/usr/one/.data
    cpus: "0.5"
    mem_limit: 512m

  app2:
    build: "./app2"
    env_file:
      - ./app2/.env
    volumes:
      - ./.data:/usr/two/.data
    cpus: "0.5"
    mem_limit: 512m
